project:
  type: book

toc: true
number-sections: true
top-level-division: chapter

bibliography: references.bib

filters:
  - pseudocode

pseudocode:
  caption-prefix: "Algorithm"
  reference-prefix: "Algorithm"
  caption-number: true

execute:
  timeout: -1 # No timeout for the entire document

book:
  title: "Learning FEM the Wrong Way"
  author: "Gregory Vernon"
  date: "8/10/2024"
  page-navigation: true
  chapters:
    - contents/index.qmd
    - part: contents/intro.qmd
    - part: contents/lectures/lecture_00/intro.qmd
      chapters:
        - contents/lectures/lecture_00/change_of_variable.qmd
        - contents/lectures/lecture_00/polynomial_roots.qmd
        - contents/lectures/lecture_00/polynomial_basis.qmd
        - contents/lectures/lecture_00/inner_products.qmd
        - contents/lectures/lecture_00/change_of_basis.qmd
        - contents/lectures/lecture_00/dirac_delta_function.qmd
    - part: contents/lectures/lecture_01/intro.qmd
      chapters:
        - contents/lectures/lecture_01/galerkin_function_approximation.qmd
        - contents/lectures/lecture_01/galerkin_function_approximation_with_boundary_conditions.qmd
    - part: contents/lectures/lecture_02/intro.qmd
      chapters:
        - contents/lectures/lecture_02/galerkin_poisson_equation.qmd
        - contents/lectures/lecture_02/galerkin_heat_equation.qmd
        - contents/lectures/lecture_02/ficks_first_law_equation.qmd
        - contents/lectures/lecture_02/euler_bernoulli_beam_equation.qmd
        # - contents/lectures/lecture_02/elastostatics_equation.qmd
        - contents/lectures/lecture_02/damped_harmonic_oscillator_equation.qmd
    - part: contents/lectures/lecture_03/intro.qmd
      chapters:
        - contents/lectures/lecture_03/piecewise_polynomials.qmd
        - contents/lectures/lecture_03/discontinuous_splines.qmd
        - contents/lectures/lecture_03/continuous_splines.qmd
        - contents/lectures/lecture_03/smooth_splines.qmd
        - contents/lectures/lecture_03/solving_pdes_with_usplines.qmd
    - part: contents/lectures/lecture_04/intro.qmd
      chapters:
        - contents/lectures/lecture_04/riemann_quadrature.qmd
        - contents/lectures/lecture_04/polynomial_quadrature.qmd
        - contents/lectures/lecture_04/gauss_quadrature.qmd
        - contents/lectures/lecture_04/moment_fitting.qmd
        - contents/lectures/lecture_04/spline_quadrature.qmd
    - part: contents/lectures/lecture_05/intro.qmd
      chapters:
        - contents/lectures/lecture_05/numerical_core_algorithms.qmd
    
    # - summary.qmd
    # - references.qmd

format:
  html:
    theme: darkly
    mainfont: "Open Sans"
    monofont: "Intel One Mono"
    # html-math-method: mathjax
    css: styles.css
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          loader: {
            load: ['[tex]/mathtools', '[tex]/physics']
          },
          tex: {
            packages: {'[+]': ['mathtools', 'physics']},
            macros: {
              Real: "{\\mathbb R}",
              Inner: ["\\left\\langle #1, #2 \\right\\rangle", 2],
              Vector: ["\\boldsymbol{\\mathit{#1}}", 1],
              Matrix: ["\\boldsymbol{\\mathrm{#1}}", 1],
              ChangeBasisOp: ["\\Matrix{R}_{\\tiny{\\Matrix{#1} \\rightarrow \\Matrix{#2}}}", 2],
              DiracDelta: ["\\delta\\left( #1 - #2 \\right)", 2],
              DiracDeltaShort: ["\\delta^{#1}_{#2}", 2],
              defequals: ["\\stackrel{\\text{def}}{=}"],
              d: ["\\mathop{}\\!{d{#1}}", 1],
              p: ["\\mathop{}\\!{\partial{#1}}", 1],
              Index: ["\\mathrm{#1}", 1],
            }
          }
        };
        </script>
  pdf:
    pdf-engine: xelatex
    latex-auto-install: true
    latex-clean: true
    latex-tinytex: false
    keep-tex: true
    mainfont: "Times New Roman"
    monofont: "JuliaMono"
    documentclass: scrreprt
    include-in-header:
      text: |
        \usepackage{amsmath}
        \usepackage{amssymb}
        \usepackage{mathpazo}
        \usepackage{mathtools}
        \usepackage{physics}
        \usepackage{bm}
        \newcommand{\Real}{\mathbb{R}}
        \newcommand{\Inner}[2]{\left\langle #1, #2 \right\rangle}
        \newcommand{\Vector}[1]{\mathbf{\mathit{#1}}}
        \newcommand{\Matrix}[1]{\boldsymbol{\mathrm{#1}}}
        \newcommand{\ChangeBasisOp}[2]{\Matrix{R}_{\tiny{\Matrix{#1}\rightarrow \Matrix{#2}}}}
        \newcommand{\DiracDelta}[2]{ \delta\left( #1 - #2 \right) }
        \newcommand{\DiracDeltaShort}[2]{ \delta^{#1}_{#2} }
        \newcommand{\defequals}{\stackrel{\text{def}}{=}}
        \newcommand{\d}{\mathop{}\!{d}}
        \newcommand{\p}{\mathop{}\!{\partial}}
        \newcommand{\Index}{\mathrm{#1}}
