project:
  type: book

toc: true
number-sections: true
top-level-division: chapter

bibliography: references.bib

filters:
  - pseudocode

pseudocode:
  caption-prefix: "Algorithm"
  reference-prefix: "Algorithm"
  caption-number: true

execute:
  timeout: -1 # No timeout for the entire document

book:
  title: "Learning FEM the Wrong Way"
  author: "Gregory Vernon"
  date: "8/10/2024"
  page-navigation: true
  chapters:
    - index.qmd
    - part: intro.qmd
    - part: lecture_00/intro.qmd
      chapters:
        - lecture_00/change_of_variable.qmd
        - lecture_00/polynomial_roots.qmd
        - lecture_00/polynomial_basis.qmd
        - lecture_00/inner_products.qmd
        - lecture_00/change_of_basis.qmd
    - part: lecture_01/intro.qmd
      chapters:
        - lecture_01/galerkin_function_approximation.qmd
        - lecture_01/galerkin_function_approximation_with_boundary_conditions.qmd
    - part: lecture_02/intro.qmd
      chapters: 
        - lecture_02/galerkin_poisson_equation.qmd
    # - summary.qmd
    # - references.qmd

# loader: {
#           load: ['[tex]/breqn']
# },
# packages: {'[+]': ['breqn']},

format:
  html:
    theme: darkly
    # html-math-method: mathjax
    css: styles.css
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          loader: {
            load: ['[tex]/mathtools']
          },
          tex: {
            packages: {'[+]': ['mathtools']},
            macros: {
              Real: "{\\mathbb R}",
              Inner: ["\\left\\langle #1, #2 \\right\\rangle", 2],
              Vector: ["\\boldsymbol{\\mathit{#1}}", 1],
              Matrix: ["\\boldsymbol{\\mathrm{#1}}", 1],
              ChangeBasisOp: ["\\Matrix{R}_{\\tiny{\\Matrix{#1} \\rightarrow \\Matrix{#2}}}", 2],
            }
          }
        };
        </script>
  pdf:
    pdf-engine: xelatex
    latex-auto-install: true
    latex-clean: true
    latex-tinytex: false
    keep-tex: true
    mainfont: "Times New Roman"
    monofont: "JuliaMono"
    documentclass: scrreprt
    include-in-header:
      text: |
        \usepackage{amsmath}
        \usepackage{amssymb}
        \usepackage{mathpazo}
        \usepackage{mathtools}
        \usepackage{bm}
        %\usepackage{breqn}
        \newcommand{\Real}{\mathbb{R}}
        \newcommand{\Inner}[2]{\left\langle #1, #2 \right\rangle}
        \newcommand{\Vector}[1]{\mathbf{\mathit{#1}}}
        \newcommand{\Matrix}[1]{\boldsymbol{\mathrm{#1}}}
        \newcommand{\ChangeBasisOp}[2]{\Matrix{R}_{\tiny{\Matrix{#1} \rightarrow \Matrix{#2}}}}
