---
jupyter: mkernel
---

```{matlab}
%| include: false
clear
setappdata(0, "MKernel_plot_backend", "inline")
setappdata(0, "MKernel_plot_format", "svg")
addpath( "../util" )
```

# Change of Variable

A core concept in finite elements is that of change of variable, which is often used to simplify mathematical operations by casting the problem into a different domain.
One such example is in integration, where change of variable appears as *integration by substitution* -- and we will later apply this concept to simplify numerical integration (quadrature)[^1].

[^1]: This will eventually lead to the idea of parent elements and mapping to/from various configurations utilized within finite element implementations, for example: *parametric*, *reference*, *current* configurations.

## Integration by substitution
Recall the chain rule for differentiation in one dimension:

::: {.callout-note icon=false}
## Chain rule

Assume the function $h(x)$ can be written as $$h(x) = f(g(x)),$$ then the chain rule is $$h^{\prime}(x) = f^{\prime}(g(x)) \cdot g^{\prime}(x).$$

:::

Given the chain rule we can define the substitution formula for integration by 

::: {.callout-note icon=false}
## Substitution formula for integration
Assume that the function, $f(x)$ has the antiderivative $F(x)$, i.e., $$F^{\prime}(x) = f(x).$$

```{=latex}
\begin{equation}
   \int_{x_0}^{x_1}{f( g(x) ) \cdot g^{\prime}(x) \d{x}} \equiv \int_{x_0}^{x_1}{F^{\prime}(g(x)) \cdot g^{\prime}(x) \d{x}} 
\end{equation}
```

Making the substitution $u = g(x)$, then leads to $\d{u} = g^{\prime}(x) \d{x}$ and results in:

```{=latex}
\begin{equation}
      \int_{x_0}^{x_1}{F^{\prime}(g(x)) \cdot g^{\prime}(x) \d{x}} \equiv \int_{u_0=g(x_0)}^{u_1=g(x_1)}{F^{\prime}(u) \d{u}} % \int_{g(x_0)}^{g(x_1)}{f(u) \d{u}} 
\end{equation}
```

Integrating we have:

```{=latex}
\begin{equation}
   \int_{u_0=g(x_0)}^{u_1=g(x_1)}{F^{\prime}(u) \d{u}} \equiv F(g(x_1)) - F(g(x_0)) \equiv \int_{g(x_0)}^{g(x_1)}{F^{\prime}(u) \d{u}}
\end{equation}
```

```{=latex}
\begin{equation}
   \int_{g(x_0)}^{g(x_1)}{F^{\prime}(u) \d{u}} \equiv \int_{g(x_0)}^{g(x_1)}{f(u) \d{u}}
\end{equation}
```

And thus we arrive at the substitution formula for integration:

```{=latex}
\begin{equation}
   \begin{split}
      \int_{x_0}^{x_1}{f( g(x) ) \cdot g^{\prime}(x) \d{x}} \equiv \int_{g(x_0)}^{g(x_1)}{f(u) \d{u}}
   \end{split}
\end{equation}
```
:::

The importance of the substitution formula for integration is that it allows us to make the following equivalencies:

::: {.callout-note icon=false}
## Equivalence of integrals under change of variables

```{=latex}
\begin{equation}
   \int_{x_0}^{x_1} f(x) \d{x} = \int_{\xi(x_0)}^{\xi(x_1)} f( x( \xi ) ) \cdot x^{\prime}(\xi) \d{\xi}
\end{equation}
```

```{=latex}
\begin{equation}
   \int_{\xi_0}^{\xi_1} g(\xi) \d{\xi} = \int_{x(\xi_0)}^{x(\xi_1)} g( \xi( x ) ) \cdot \xi^{\prime}(x) \d{x} 
\end{equation}
```
:::


## Affine map
An affine map is any mapping that preserves collinearity and ratios of distances[@weisstein_affine] or, to put another way, is a combination of a linear transformation and a translation.

::: {.callout-note icon=false}
## Affine map
An affine map $\xi: \Real^n \rightarrow \Real^n$ has the form:

 ```{=latex}
\begin{equation}
   \xi(\Vector{x}) = \Matrix{A}\Vector{x} + \Vector{b},
\end{equation}
```

where $\Vector{x} \in \Real^n$ and $\Matrix{A}$ is a linear transformation of $\Real^n$.
:::

Some common affine mappings, in geometric terms, include scaling, rotation, translation, and shear.
The affine map that we first concern ourselves with is the one-dimensional affine map, which combines scaling and translation:

```{=latex}
\begin{equation}
   \xi(x) = \Scalar{a} x + \Scalar{b}, \quad \Scalar{a}, \Scalar{b} \in \Real{}
\end{equation}
```

There are two unknowns in this map, $\Scalar{a}$ and $\Scalar{b}$, which we can solve for by creating a system of two unique equations -- if we know the values of $x$ and $\xi$ in both:

```{=latex}
\begin{equation}
   \begin{split}
      \Scalar{\xi}_0 &= \Scalar{a} \Scalar{x}_0 + \Scalar{b} \\
      \Scalar{\xi}_1 &= \Scalar{a} \Scalar{x}_1 + \Scalar{b} \\
   \end{split}
\end{equation}
```

Which we can rewrite in matrix form:

```{=latex}
\begin{equation}
   \begin{bmatrix}
      \Scalar{\xi}_0 \\
      \Scalar{\xi}_1 \\
   \end{bmatrix}
   %
   =
   %
   \begin{bmatrix}
      \Scalar{x}_0 & 1 \\
      \Scalar{x}_1 & 1 \\
   \end{bmatrix}
   %
   \begin{bmatrix}
      a \\
      b \\
   \end{bmatrix}
\end{equation}
```

In practice, this affine mapping often arises in applications where we have two domains in $\Real^1$ upon which we impose the affine map:

```{=latex}
\begin{equation}
   \begin{split}
      x   &= \ClosedDomainOneDim{\Scalar{x}_0}{\Scalar{x}_1} \\
      \xi &= \ClosedDomainOneDim{\Scalar{\xi}_0}{\Scalar{\xi}_1} \\
      \xi &= \xi(x)
   \end{split}
\end{equation}
```

And since we know, trivially, the mapping at both boundaries we can fill-in our two equations and solve for the unknowns.

::: {.callout-tip icon=false}
## Example: Computing an affine map
Consider the two domains:

```{=latex}
\begin{equation}
   \begin{split}
      x   &= \ClosedDomainOneDim{2}{7} \\
      \xi &= \ClosedDomainOneDim{-1}{1} \\
   \end{split}
\end{equation}
```

For which we wish to define the affine map $\xi(\Scalar{x})$.

```{=latex}
\begin{align*}
   \begin{bmatrix}
      -1 \\
      1 \\
   \end{bmatrix}
   &=
   \begin{bmatrix}
      2 & 1 \\
      7 & 1\\
   \end{bmatrix}
   \begin{bmatrix}
      a \\
      b
   \end{bmatrix} \\
   %%%%%%%%%%%%%%%%
   \begin{bmatrix}
      a \\
      b
   \end{bmatrix}
   &=
   \left(
      \begin{bmatrix}
         2 & 1 \\
         7 & 1\\
      \end{bmatrix}
   \right)^{-1}
   \begin{bmatrix}
      -1 \\
      1 \\
   \end{bmatrix} \\
   %%%%%%%%%%%%%%%%
   \begin{bmatrix}
      a \\
      b
   \end{bmatrix}
   &=
   \begin{bmatrix}
      \frac{-1}{5} & \frac{1}{5} \\
      \frac{7}{5} & \frac{-2}{5}\\
   \end{bmatrix}
   \begin{bmatrix}
      -1 \\
      1 \\
   \end{bmatrix} \\
   %%%%%%%%%%%%%%%%
   \begin{bmatrix}
      a \\
      b
   \end{bmatrix}
   &=
   \begin{bmatrix}
      \frac{2}{5} \\
      \frac{-9}{5}
   \end{bmatrix}
\end{align*}
```

Inserting the solution into the affine map yields:

```{=latex}
\begin{equation}
   \xi(x) = \frac{2}{5} x - \frac{9}{5}
\end{equation}
```
:::

```{matlab}
%| echo: false
range = @(vec) max( vec ) - min( vec );                      
ax2norm = @(x,y,ax) [ ax.Position(3)*((x-ax.XLim(1))./range(ax.XLim))+ ax.Position(1)
                      ax.Position(4)*((y-ax.YLim(1))./range(ax.YLim))+ ax.Position(2) ];
                      
fig = figure;
ax = gca; ax.NextPlot = "add";
plot( ax, [2, 7], [ 1, 1], Color="w", LineStyle="None", MarkerSize=16, Marker="|", MarkerFaceColor="w", MarkerEdgeColor="w" )
plot( ax, [2, 7], [ 1, 1], Color="w", LineWidth=1, MarkerSize=10, Marker="square", MarkerFaceColor="w", MarkerEdgeColor="w" )
text( ax, 2, 0.9, "$2$", Interpreter="latex", FontSize=24, VerticalAlignment="top", HorizontalAlignment="center" )
text( ax, 7, 0.9, "$7$", Interpreter="latex", FontSize=24, VerticalAlignment="top", HorizontalAlignment="center" )
text( ax, 4.5, 1.5, "$x$", Interpreter="latex", FontSize=24, HorizontalAlignment="center" )

plot( ax, [-1, 1], [ 0, 0], Color="w", LineWidth=1, MarkerSize=10, Marker="square", MarkerFaceColor="w", MarkerEdgeColor="w" )
text( ax, -1, -0.1, "$-1$", Interpreter="latex", FontSize=24, VerticalAlignment="top", HorizontalAlignment="center" )
text( ax,  1, -0.1, "$1$", Interpreter="latex", FontSize=24, VerticalAlignment="top", HorizontalAlignment="center" )
text( ax,  0, -0.5, "$\xi$", Interpreter="latex", FontSize=24, HorizontalAlignment="center" )

ax.FontSize=24;
ax.XLim = [-2, 8];
ax.YLim = [-1, 2];
ax.XAxis.Visible = "off";
ax.YAxis.Visible = "off";
ax.XAxisLocation = "origin";
ax.Box = "off";
ax.XLimitMethod = "padded";
ax.TickDir = "both";
ax.Color = fig.Color;

xy_1 = ax2norm( 3, 0.9, ax );
xy_2 = ax2norm( -0.6, 0.1, ax );
annotation( "textarrow", [xy_1(1), xy_2(1)], [xy_1(1), xy_2(1)], String="$\xi(x)$", Interpreter="latex", Parent=ax, Units="Normalized" );

```

We can modify our substitution formula for integration to account for an affine map.
Note that as our affine map, $\frac{\d{\xi}}{\d{x}}$, is equivalent to a Jacobian matrix of size $1\times1$ we will refer to this term as the *Jacobian*, $\Jacobian$.
Note that because our affine map is linear, its derivative will be a constant and thus we can apply the integration rule for constants to pull the Jacobian out of the integral


::: {.callout-note icon=false}
## Substitution formula for integration with affine map
If we let $u = \xi(x)$ then we have

```{=latex}
\begin{equation}
   \begin{split}
      \int_{x_0}^{x_1}{f( \xi(x) ) \cdot \xi'(x) \d{x}} &\equiv \int_{\xi(x_0)}^{\xi(x_1)}{f(\xi) \d{\xi}} \equiv \int_{\xi(x_0)}^{\xi(x_1)}{f(\xi) \d{\xi}}\\
      %
      \int_{x_0}^{x_1}{f( \xi(x) ) \cdot \xi'(x) \d{x}} &\equiv \int_{\xi(x_0)}^{\xi(x_1)}{f(\xi) \d{\xi}} \equiv \int_{\xi(x_0)}^{\xi(x_1)}{f(\xi) \d{\xi}}\\
   \end{split}
\end{equation}
```
:::



```{=latex}
\begin{equation}
   \int_{a}^{b}{f( \Scalar{a} x + \Scalar{b} ) \cdot a \d{x}} \equiv \int_{\xi(a)}^{\xi(b)}{f(\xi) \d{\xi}} 
\end{equation}
```


Let's now write a function that simply maps from some domain to some other domain using change of variable.

```{matlab}
%| echo: true
%| output: false
function to_value = ChangeOfVariable( from_value, from_domain, to_domain )
    % ASSEMBLE LINEAR SYSTEM
    A = [ from_domain(1) 1; from_domain(2) 1 ];
    b = [ to_domain(1); to_domain(2) ];
    % SOLVE FOR COEFFICIENTS
    sol = A \ b;
    % COMPUTE MAPPING
    to_value = sol(1) * from_value + sol(2);
end
```

Let's see this function in action!

```{matlab}
%| echo: true
from_domain = sym( [-1, 1] );
to_domain = sym( [2, 7] );
from_values = sym( [-1, -0.5, 0, 0.5, 1] );

for ii = 1 : length( from_values )
    to_values(ii) = ChangeOfVariable( from_values(ii), from_domain, to_domain );
end
display( from_values )
display( to_values )
```

Now let's see what happens when we use the change of variable in an actual function, using the mapping $x(\xi)$:

::: {.callout-tip icon=false}
## Example: $f(\xi) \rightarrow g(x(\xi))$
```{=latex}
\begin{align*}
   f(\xi) &= -\frac{128 x^4}{1875} + \frac{2144 x^3}{1875} - \frac{12592 x^2}{1875} + \frac{30736 x}{1875} - \frac{8736}{625} \\
   x(\xi) &= \frac{5}{2} \xi + \frac{9}{2} \\
   g( x(\xi) ) &= -\frac{8 \xi^4}{3} - \frac{4 \xi^3}{3} + \frac{8\xi^2}{3} + \frac{4 \xi}{3} \\ 
\end{align*}
```

```{matlab}
%| output: false
x = sym( "x", "real" );
x_domain = sym( [2, 7] );
xi = sym( "xi", "real" );
xi_domain = sym( [-1, 1] );

f_x = - (128*x^4)/1875 + (2144*x^3)/1875 - (12592*x^2)/1875 + (30736*x)/1875 - 8736/625;
x_xi = ChangeOfVariable( xi, xi_domain, x_domain );
f_x_xi = subs( f_x, x, x_xi );
```

```{matlab}
%| echo: false
figure
subplot( 2, 1, 1 )
hold on
cmap = lines(2);
farea( f_x, [2, 3.25], ax=gca, FaceColor=cmap(1,:) );
farea( f_x, [3.25, 4.5], ax=gca, FaceColor=cmap(2,:) );
farea( f_x, [4.5, 7], ax=gca, FaceColor=cmap(1,:) );
fplot( f_x, [-2, 2], LineStyle=":", LineWidth=2, SeriesIndex=1 )
fplot( f_x, [2, 7],  LineStyle="-", LineWidth=2, SeriesIndex=1 )
fplot( f_x, [7, 8],  LineStyle=":", LineWidth=2, SeriesIndex=1 )
ax1 = gca;
ax1.XLim = [-2, 8];
ax1.YLim = [-0.5, 1.5];
ax1.XLabel.String = "$x$";
ax1.XLabel.Interpreter = "latex";
ax1.YLabel.String = "$f(x)$";
ax1.YLabel.Interpreter = "latex";

subplot( 2, 1, 2 )
hold on
farea( f_x_xi, [-1, -0.5], ax=gca, FaceColor=cmap(1,:) );
farea( f_x_xi, [-0.5, 0], ax=gca, FaceColor=cmap(2,:) );
farea( f_x_xi, [0, 1], ax=gca, FaceColor=cmap(1,:) );
fplot( f_x_xi, [-2, -1], LineStyle=":", LineWidth=2, SeriesIndex=1 )
fplot( f_x_xi, [-1, 1], LineStyle="-", LineWidth=2, SeriesIndex=1 )
fplot( f_x_xi, [1, 8],  LineStyle=":", LineWidth=2, SeriesIndex=1 )
ax2 = gca;
ax2.XLim = [-2, 8];
ax2.YLim = [-0.5, 1.5];
ax2.XLabel.String = "$\xi$";
ax2.XLabel.Interpreter = "latex";
ax2.YLabel.String = "$g(\xi(x))$";
ax2.YLabel.Interpreter = "latex";
```

We compute the integral of $f(x)$ and compare it against the result from the substitution formula for integration:

```{matlab}
%| output: false
%| echo: false

I1 = int( f_x, x );
I2 = int( f_x_xi, xi ) * diff( x_xi, xi );
```

```{=latex}
\begin{equation*}
   \begin{split}
      \int_{2}^{7}{ f(x) \d{x} } &\equiv \int_{2}^{7}{ -\frac{128 x^4}{1875} + \frac{2144 x^3}{1875} - \frac{12592 x^2}{1875} + \frac{30736 x}{1875} - \frac{8736}{625} \d{x} } \\
      %
      &= \left[ -\frac{128 x^5}{9375} + \frac{536 x^4}{1875} - \frac{12592 x^3}{5625} + \frac{15368 x^2}{1875} - \frac{8736 x}{625} \right]_2^7 \\
      %
      &= \frac{16}{9} = 1.\overline{777}
   \end{split}
\end{equation*}
```

And comparing against the change of variables approach:

```{=latex}
\begin{equation*}
   \begin{split}
      \int_{x(-1)}^{x(1)}{ g( \xi(x) ) \frac{ \d{\xi(x)}}{\d{x}} \d{\xi} } &\equiv \int_{2}^{7}{ \left( -\frac{8 \xi^4}{3} - \frac{4 \xi^3}{3} + \frac{8 \xi^2}{3} + \frac{4 \xi }{3} \right) \frac{5}{2} \d{\xi} } \\
      %
      &= \left[ -\frac{4 \xi^5}{3} - \frac{5 \xi^4}{6} + \frac{20 \xi^3}{9} + \frac{5 \xi^2}{3} \right]_{2}^{7} \\
      %
      &= \frac{16}{9} = 1.\overline{777}
   \end{split}
\end{equation*}
```
:::

And again on another function, this time using the mapping $\xi(x)$:

::: {.callout-tip icon=false}
## Example: $f(\xi) \rightarrow g(\xi(x))$
First let's choose a function defined over $\xi$ and map it to $x$, using the mapping $\xi(x)$.

```{=latex}
\begin{align*}
   f(\xi) &= \frac{\exp\left( -\frac{ (\xi - \mu)^2 }{ 2\sigma^2 } \right)}{\sqrt{ 2\pi\sigma^2}} \\
   \\
   \xi(x) &= \frac{2}{5} x - \frac{9}{5} \\
   \\
   f( \xi(x) ) &= \frac{\exp\left( -\frac{ \left( \left( \frac{2}{5} x - \frac{9}{5} \right) - \mu \right)^2 }{ 2\sigma^2 } \right)}{\sqrt{2\pi\sigma^2}}
\end{align*}
```

Where, for this example, $\mu = 0$ and $\sigma = \frac{3}{4}$.

```{matlab}
%| output: false
x = sym( "x", "real" );
x_domain = sym( [2, 7] );
xi = sym( "xi", "real" );
xi_domain = sym( [-1, 1] );

sigma = sym( 0.75 );
mu = sym( 0 );
f_xi = ( 1 / ( sqrt( 2 * pi * sigma^2 ) ) ) * exp( - ( xi - mu )^2 / ( 2 * sigma^2 ) );
xi_x = ChangeOfVariable( x, x_domain, xi_domain );
f_xi_x = subs( f_xi, xi, xi_x );
```

```{matlab}
%| echo: false
figure
subplot( 2, 1, 1 )
hold on
cmap = lines(2);
farea( f_xi, [-1, 1], ax=gca, FaceColor=cmap(1,:) );
fplot( f_xi, [-2, -1], LineStyle=":", LineWidth=2, SeriesIndex=1 )
fplot( f_xi, [-1, 1],  LineStyle="-", LineWidth=2, SeriesIndex=1 )
fplot( f_xi, [1, 8],  LineStyle=":", LineWidth=2, SeriesIndex=1 )
ax1 = gca;
ax1.XLim = [-2 8];
ax1.XLabel.String = "$\xi$";
ax1.XLabel.Interpreter = "latex";
ax1.YLabel.String = "$f(\xi)$";
ax1.YLabel.Interpreter = "latex";

subplot( 2, 1, 2 )
hold on
farea( f_xi_x, [2, 7], ax=gca, FaceColor=cmap(1,:) );
fplot( f_xi_x, [-2, 2], LineStyle=":", LineWidth=2, SeriesIndex=1 )
fplot( f_xi_x, [2, 7],  LineStyle="-", LineWidth=2, SeriesIndex=1 )
fplot( f_xi_x, [7, 8],  LineStyle=":", LineWidth=2, SeriesIndex=1 )
ax2 = gca;
ax2.XLim = [-2 8];
ax2.XLabel.String = "$x$";
ax2.XLabel.Interpreter = "latex";
ax2.YLabel.String = "$g(\xi(x))$";
ax2.YLabel.Interpreter = "latex";
```

And now let's compute the integral of $f(x)$ and compare it against the result from the substitution formula for integration:

```{matlab}
%| output: false
%| echo: false

I1 = int( f_xi, xi );
I2 = int( f_xi_x * diff( xi_x, x ), x );
```

```{=latex}
\begin{equation*}
   \begin{split}
      % ( 1 / ( sqrt( 2 * pi * sigma^2 ) ) ) * exp( - ( x - mu )^2 / ( 2 * sigma^2 ) )
      \int_{-1}^{1}{ f(\xi) \d{\xi} } &\equiv \int_{-1}^{1}{\frac{ \exp\left( -\frac{ ( \xi - 0 )^2}{2 \left( \frac{3}{4} \right)^2 }\right) }{\sqrt{2\pi \left( \frac{3}{4} \right)^2}}  \d{\xi} } \\
      \\
      &= \left[ \frac{\erf\left( \frac{2 \sqrt{2} \xi}{3} \right)}{2} \right]_{-1}^{1} \\
      \\
      &= \erf\left( \frac{2 \sqrt{2}}{3} \right) \approx 0.8176
   \end{split}
\end{equation*}
```

And comparing against the change of variables approach:

```{=latex}
\begin{equation*}
   \begin{split}
      % ( 1 / ( sqrt( 2 * pi * sigma^2 ) ) ) * exp( - ( x - mu )^2 / ( 2 * sigma^2 ) )
      \int_{\xi(2)}^{\xi(7)}{ g(\xi(x)) \cdot \xi^{\prime}(x) \d{x} } &\equiv \int_{-1}^{1}{\frac{ \exp\left( -\frac{ \left( \left( \frac{2}{5} x - \frac{9}{5} \right) - 0 \right)^2}{2 \left( \frac{3}{4} \right)^2 }\right) }{\sqrt{2\pi \left( \frac{3}{4} \right)^2}} \cdot \frac{2}{5}  \d{x} } \\
      \\
      &= \left[ \frac{\erf\left( \sqrt{2} \left( \frac{4 x}{15} - \frac{6}{5} \right) \right)}{2} \right]_{-1}^{1} \\
      \\
      &= \erf\left( \frac{2 \sqrt{2}}{3} \right) \approx 0.8176
   \end{split}
\end{equation*}
```

:::


### References

::: {#refs}
:::