---
jupyter: mkernel
---

```{matlab}
%| include: false
clear
setappdata(0, "MKernel_plot_backend", "inline")
setappdata(0, "MKernel_plot_format", "svg")
```

# Inner Products

Just as measuring quanitities is critical in engineering and science, so to is it important in mathematics.
For example, when working with vectors one often wishes to know "how similar are these two vectors?" --- a question that every STEM practitioner knows to solve via the *dot product*.
It is perhaps unfortunate, however, that far fewer STEM practitioners understand the dot product as an *inner product*.
In fact, I would posit that very few engineers even know what the inner product is and how incredibly useful it is to engineering.
It is my belief that this lack of understanding might come from simply a disconnect between the theory and application, one that I hope to at least partially correct.

As an engineer myself, I like to think of *tools* that I can use to solve problems --- we often give tools names that describe what they do: hammer, screwdriver, pliers, vice grip, drill, etc.
While I'm not going to rename the inner product, let me at least provide a simplified description of what this tool does:

Inner Product
: a tool that allows us to compare two objects of similar type, allowing us to measure them.

There is obviously a more rigorous definition of an inner product, similar to how there's a more rigorous definition of "hammer" than

Hammer
: a tool that allows us to drive a nail into solid material, allowing us to join objects.

You could use a book, a shoe, a smartphone, or a gold bar to drive a nail in this manner but if you bought a hammer online and what arrived was a hardcover book you'd, understandably, be upset.
At the end of this chapter I'll provide a wrote description of the inner product that will allow you to recognize an operation "in the wild" as an inner product (or not).
But for now, let me just show you how my simplified description of the inner product works.

## Notation

Before we do that though, let me define the notation that I will use to represent the inner product between two objects:

$$
\Inner{\cdot}{\cdot}
$$

where each "$\cdot$" is a placeholder for one of the two objects.

## The Inner Product on the Real Numbers

Overly simplified, the real numbers, represented by $\Real$, are the types of numbers you use 99.999% in everyday life.
Numbers like 0, or 1, or 147... but also numbers like 1.4 and -0.9, and $\sqrt{2}$ and $\pi$.

$$
\Inner{a}{b} := ab, \quad a,b \in \Real
$$

This is simply *scalar multiplication* between two numbers, how does this let us compare two objects?
We can compare $\Inner{a}{b}$ against $\Inner{b}{b}$ by dividing the former by the latter:

$$
\frac{\Inner{a}{b}}{\Inner{b}{b}}
$$

Which gives us the comparisons:

- $\frac{\Inner{a}{b}}{\Inner{b}{b}} = 1$
  - This tells us that $a$ is equal to $b$
- $\frac{\Inner{a}{b}}{\Inner{b}{b}} = ^{-}1$
  - This tells us that $a$ is the additive inverse of $b$.
- $\frac{\Inner{a}{b}}{\Inner{b}{b}} > 1$
  - This tells us that the magnitude of $a$ is larger than the magnitude of $b$, i.e., $\|a\| > \|b\|$.
- $\frac{\Inner{a}{b}}{\Inner{b}{b}} < 1$
  - This tells us that the magnitude of $a$ is smaller than the magnitude of $b$, i.e., $\|a\| < \|b\|$.

Furthermore, if we simplify the expression comparing the two inner products, $\frac{\Inner{a}{b}}{\Inner{b}{b}}$, we find $\frac{a \cdot b}{b \cdot b} = \frac{a}{b}$ --- the inner product is providing us a *ratio* between the two numbers.
So how is this useful?
I'll admit this seems a bit contrived but consider this example:

Imagine that you have two unknown values.
You are able to compare them against each other using the inner product, but do not yet actually know the value of either.
You compare the two inner products and find $\frac{\Inner{a}{b}}{\Inner{b}{b}} = -\frac{1}{16}$.
Now, sometime later you are able to compare $a$ against the number $2.5$ and find $\frac{\Inner{2.5}{a}}{\Inner{2.5}{2.5}} = -1.6$.
We now *instantly* know that $a = -.25$ and $b = 4$.
The inner product allowed us to compare two objects, and when you can compare two objects *you can measure them*.
But perhaps this was too simple to be convincing, afterall it is, as we said, simply scalar multiplication and division.
Let's look at a slightly more difficult use-case:

## The Inner Product of Real Vectors

If we have two vectors consisting of real numbers

```{=latex}
\begin{align*}
  \vec{x} = [ x_0, \cdots, x_n ]^T, &\quad i \in 0:n \\
  \vec{y} = [ y_0, \cdots, y_n ]^T, &\quad i \in 0:n \\
\end{align*}
```

the inner product, which we previously stated is also known as the "dot product", is defined as

```{=latex}
\begin{equation*}
\Inner{\vec{x}}{\vec{y}} = \vec{x}^T \vec{y} \sum_{i=0}^{n-1} x_i y_i = x_0 y_0 + \cdots + x_{n-1} y_{n-1}
\end{equation*}
```

And again, we ask the question "how does the inner product allow us to compare and/or measure vectors?"
And again, we answer with an example.
As before we can compare the vectors against each other via

```{=latex}
\begin{equation*}
  \frac{\Inner{\vec{x}}{\vec{y}}}{\Inner{\vec{y}}{\vec{y}}}
\end{equation*}
```

Which gives us the comparisons:

- $\frac{\Inner{\vec{x}}{\vec{y}}}{\Inner{\vec{y}}{\vec{y}}} = 1$
  - This tells us that $\vec{x}$ is equivalent to $\vec{y}$, having the same magnitude and direction.
- $\frac{\Inner{\vec{x}}{\vec{y}}}{\Inner{\vec{y}}{\vec{y}}} = ^{-}1$
  - This tells us that $\vec{x}$ is has equivalent magnitude to $\vec{y}$, but in the opposite direction.
- $\frac{\Inner{\vec{x}}{\vec{y}}}{\Inner{\vec{y}}{\vec{y}}} > 1$
  - This tells us that the magnitude of $\vec{x}$ is larger than the magnitude of $a$, i.e., $\|b\| > \|a\|$.
- $\frac{\Inner{\vec{x}}{\vec{y}}}{\Inner{\vec{y}}{\vec{y}}} < 1$
  - This tells us that the magnitude of $b$ is smaller than the magnitude of $a$, i.e., $\|b\| < \|a\|$.

## The Inner Product of Real Functions
Given two real functions[^2], $f$ and $g$, the inner product is

```{=latex}
\begin{equation*}
  \Inner{f}{g}_{L^2} \coloneqq \int_{\Omega}{ f g } \ d\Omega
\end{equation*}
```

which is also known as the $L^2$ inner product.
The norm induced by the $L^2$ inner product is the $L^2$-norm

```{=latex}
\begin{equation*}
  \| f \|_{L^2} \coloneqq \sqrt{ \Inner{f}{f} }
\end{equation*}
```

Since we'll be dealing with the $L^2$ inner product quite a bit, let's consider some examples

### Example 4.4.1

```{matlab}
%| output: false
x = sym( "x", "real" );
f = sin( x );
g = sin( x );
L2 = int( f * g );
```

```{=latex}
\begin{align*}
  f(x) &= \sin(x) \\
  g(x) &= \sin(x) \\
  \Inner{f(x)}{g(x)} &= \frac{1}{2} ( x - \sin(x) \cos(x) ) \\
\end{align*}
```

```{matlab}
%| echo: false
domain = sym( [0, 2*pi] );

figure
subplot( 2, 1, 1 )
hold on
fplot( f, double( domain ), LineWidth=2, DisplayName="$f(x)$" )
fplot( g, double( domain ), LineWidth=2, DisplayName="$g(x)$" )
legend()

subplot( 2, 1, 2 )
fplot( L2, double( domain ), LineWidth=2, DisplayName="$\langle f(x), g(x) \rangle$" )
legend()
```

Where evaluating the inner product provides us with a function of the domain:

And, for example, the inner product on the domain $[0,2\pi]$ is then

```{matlab}
%| output: false
f = sin( x );
g = sin( x );
L2 = int( f * g, domain );
```

```{=latex}
\begin{equation}
  \Inner{f(x)}{g(x)}_{[0, 2\pi]} = \pi
\end{equation}
```


### Example 4.4.2

```{matlab}
%| output: false
f = sin( x )
g = -1 * sin( x )
L2 = int( f * g )
```

Where evaluating the inner product provides us with a function of the domain:

```{=latex}
\begin{align*}
  f(x) &= \sin(x) \\
  g(x) &= -\sin(x) \\
  \Inner{f(x)}{g(x)} &= \frac{1}{2} ( \sin(x) \cos(x) + x) \\
\end{align*}
```

```{matlab}
%| echo: false
domain = sym( [0, 2*pi] );

figure
subplot( 2, 1, 1 )
hold on
fplot( f, double( domain ), LineWidth=2, DisplayName="$f(x)$" )
fplot( g, double( domain ), LineWidth=2, DisplayName="$g(x)$" )
legend()

subplot( 2, 1, 2 )
fplot( L2, double( domain ), LineWidth=2, DisplayName="$\langle f(x), g(x) \rangle$" )
legend()
```
And, for example, the inner product on the domain $[0,2\pi]$ is then

```{=latex}
\begin{equation}
  \Inner{f(x)}{g(x)}_{[0, 2\pi]} = -\pi
\end{equation}
```

### Example 4.4.3

```{matlab}
%| output: false
f = sin( x )
g = cos( x )
L2 = int( f * g )
```

Where evaluating the inner product provides us with a function of the domain:

```{=latex}
\begin{align*}
  f(x) &= \sin(x) \\
  g(x) &= \cos(x) \\
  \Inner{f(x)}{g(x)} &= \frac{\sin(x)^2}{2} \\
\end{align*}
```

```{matlab}
%| echo: false
domain = sym( [0, 2*pi] );

figure
subplot( 2, 1, 1 )
hold on
fplot( f, double( domain ), LineWidth=2, DisplayName="$f(x)$" )
fplot( g, double( domain ), LineWidth=2, DisplayName="$g(x)$" )
legend()

subplot( 2, 1, 2 )
fplot( L2, double( domain ), LineWidth=2, DisplayName="$\langle f(x), g(x) \rangle$" )
legend()
```
And, for example, the inner product on the domain $[0,2\pi]$ is then

```{=latex}
\begin{equation}
  \Inner{\sin(x)}{\sin(x)}_{[0, 2\pi]} = 0
\end{equation}
```

### Example 4.4.4

```{matlab}
%| output: false
f = sin( x )
g = sin( 2*x )
L2 = int( f * g )
```

Where evaluating the inner product provides us with a function of the domain:

```{=latex}
\begin{align*}
  f(x) &= \sin(x) \\
  g(x) &= \sin(2x) \\
  \Inner{f(x)}{g(x)} &= \frac{\sin(x) - \sin(x)\cos(2x)}{3} \\
\end{align*}
```

```{matlab}
%| echo: false
domain = sym( [0, 2*pi] );

figure
subplot( 2, 1, 1 )
hold on
fplot( f, double( domain ), LineWidth=2, DisplayName="$f(x)$" )
fplot( g, double( domain ), LineWidth=2, DisplayName="$g(x)$" )
legend()

subplot( 2, 1, 2 )
fplot( L2, double( domain ), LineWidth=2, DisplayName="$\langle f(x), g(x) \rangle$" )
legend()
```

And, for example, the inner product on the domain $[0,2\pi]$ is then

```{=latex}
\begin{equation}
  \Inner{f(x)}{g(x)}_{[0, 2\pi]} = 0
\end{equation}
```

[^2]: Functions whose range is in the real numbers