---
jupyter: mkernel
---

```{matlab}
%| include: false
clear
setappdata(0, "MKernel_plot_backend", "inline")
setappdata(0, "MKernel_plot_format", "svg")
```

# Polynomial Basis
What is a polynomial?
Chances are that you have a pretty good basic understanding of polynomials, you know a polynomial when you see it.
But you may not have considered polynomials as being a vector space, of each polynomial function being describable as a linear combination of coefficients and a polynomial basis.
Let's investigate.

```{matlab}
%| output: false
function domain = GetPolynomialParametricDomain( basis_name )
    switch basis_name
        case "Bernstein"
            domain = [0, 1];
        case "Chebyshev"
            domain = [-1, 1];
        case "Lagrange"
            domain = [-1, 1];
        case "Legendre"
            domain = [-1, 1];
        case "Lagrange-Legendre"
            domain = [-1, 1];
        case "Monomial"
            domain = [0, 1];
    end
end
```

## The Monomial Basis
The polynomial basis probably most familiar to the reader is the *monomial basis*, sometimes called the *power basis*.

```{matlab}
%| output: false
function basis = MonomialBasis( degree, variate, domain )
    param_domain = GetPolynomialParametricDomain( "Monomial" )
    variate = ChangeOfVariable( variate, domain, param_domain );
    basis = sym( zeros( degree + 1, 1 ) );
    for ii = 1 : degree + 1
        basis(ii) = variate^( ii - 1 );
    end
end
```

These basis polynomials are, as the name suggests, the familiar monomials and, as such, is normally defined over the unit domain $[0,1]$.

```{matlab}
%| output: false
x = sym( "x", "real" );
degree = 3;
domain = sym( [0, 1] );
monomial_basis = MonomialBasis( degree, x, domain );
```

```{=latex}
\begin{equation*}
    \Matrix{M}^3(x)
    =
    \begin{bmatrix}
        x^0 \\
        x^1 \\
        x^2 \\
        x^3 \\
    \end{bmatrix}
\end{equation*}
```

```{matlab}
%| echo: false

x = sym( "x", "real" );
domain = sym( [0, 1] );

figure
for degree = 0 : 3
    subplot( 2, 2, degree + 1 )
    hold on
    monomial_basis = MonomialBasis( degree, x, domain );
    for ii = 1 : length( monomial_basis )
        fplot( monomial_basis(ii), double( domain ), LineWidth=2, DisplayName="$M_" + num2str(ii) + "$" )
    end
    ax = gca;
    ax.YLim = [0, 1];
    legend( Location="northoutside", Orientation="horizontal" )
end
```

However, including the change of variable operator in its construction allows for defining the monomial basis over any domain, such as the bi-unit domain $[-1,1]$

```{=latex}
\begin{equation*}
    \Matrix{M}^3(x)
    =
    \begin{bmatrix}
        \left( \frac{x + 1}{2} \right)^0 \\
        \left( \frac{x + 1}{2} \right)^1 \\
        \left( \frac{x + 1}{2} \right)^2 \\
        \left( \frac{x + 1}{2} \right)^3 \\
    \end{bmatrix}
\end{equation*}
```

```{matlab}
%| echo: false
figure
subplot( 2, 1, 1 )
hold on
for ii = 1 : length( monomial_basis )
    fplot( monomial_basis(ii), [-1, 1], LineWidth=2, DisplayName="$M_" + num2str(ii) + "$" )
end
ax1 = gca;
ax1.XLim = [-1, 1];

subplot( 2, 1, 2 )
domain = sym( [-1, 1] );
monomial_basis = MonomialBasis( degree, x, domain );
hold on
for ii = 1 : length( monomial_basis )
    fplot( monomial_basis(ii), double( domain ), LineWidth=2, DisplayName="$M_" + num2str(ii) + "$" )
end
```

## The Lagrange Basis

The Lagrange basis is a so-called *interpolatory basis* and has wide applications in interpolation and approximation.
In fact, because of its interpolation properties it is the *de facto* standard basis used in traditional finite element codes.
It also gives rise to the Lagrange interpolating polynomial.
Note that the Lagrange basis is usually defined over the bi-unit domain $[-1, 1]$.

```{matlab}
%| output: false
function basis = LagrangeBasis( degree, variate, domain )
    node = linspace( domain(1), domain(2), degree + 1 );
    basis = sym( zeros( degree+1, 1 ) );
    for ii=1:degree+1
        basis(ii) = variate ^ 0;
        for jj = 1 : degree + 1
            if ii ~= jj
                basis(ii) = basis(ii) * ( ( variate - node(jj) ) / ( node(ii) - node(jj) ) );
            end
        end
    end
end
```

```{=latex}
\begin{align*}
    \begin{array}{ll}
        \Matrix{L}^0(x)
        =
        \begin{bmatrix}
            x^0 \\
        \end{bmatrix}
        %%%%%%%%%%%%%%%%
        &
        %%%%%%%%%%%%%%%%
        \Matrix{L}^1(x)
        =
        \begin{bmatrix}
            -\frac{x^1}{2} + \frac{x^0}{2}\\
             \frac{x^1}{2} + \frac{x^0}{2}
        \end{bmatrix}
        %%%%%%%%%%%%%%%%
        \\
        %%%%%%%%%%%%%%%%
        \Matrix{L}^2(x)
        =
        \begin{bmatrix}
            \frac{x^2}{2} - \frac{x^1}{2}\\
            x^0-x^2 \\
            \frac{x^2}{2} + \frac{x^1}{2}
        \end{bmatrix}
        %%%%%%%%%%%%%%%%
        &
        %%%%%%%%%%%%%%%%
        \Matrix{L}^3(x)
        =
        \begin{bmatrix}
            -\frac{9x^3}{16}  + \frac{9x^2}{16} + \frac{x^1}{16}   - \frac{x^0}{16}  \\
             \frac{27x^3}{16} - \frac{9x^2}{16} - \frac{27x^1}{16} + \frac{9x^0}{16} \\
            -\frac{27x^3}{16} - \frac{9x^2}{16} + \frac{27x^1}{16} + \frac{9x^0}{16} \\
             \frac{9x^3}{16}  + \frac{9x^2}{16} - \frac{x^1}{16}   - \frac{x^0}{16}
        \end{bmatrix}
    \end{array}
\end{align*}
```

```{matlab}
%| echo: false
x = sym( "x", "real" );
domain = sym( [-1, 1] );

figure
for degree = 0 : 3;
    subplot( 2, 2, degree + 1 )
    hold on
    lagrange_basis = LagrangeBasis( degree, x, domain );
    % latex( expand( lagrange_basis ) )
    for ii = 1 : length( lagrange_basis )
        fplot( lagrange_basis(ii), double( domain ), LineWidth=2, DisplayName="$L_" + num2str(ii) + "$" )
    end
    ax = gca;
    ax.YLim = [-0.5, 1.5];
    legend( Location="northoutside", Orientation="horizontal" )
end
```

## The Bernstein Basis

The Bernstein basis is both a historically significant basis and currently a vital basis in the fields of approximation, computer-aided design, computer graphics, and even computer font design.
It forms the foundation for such things as Bezier curves, B-splines, NURBS, and isogeometric analysis.
We will talk more about these later.

Note that the Bernstein basis is usually defined over the unit domain $[0,1]$.

```{matlab}
%| output: false
function basis = BernsteinBasis( degree, variate, domain )
    param_domain = GetPolynomialParametricDomain( "Bernstein" )
    variate = ChangeOfVariable( variate, domain, param_domain );
    basis = sym( zeros( degree + 1, 1 ) );
    for a=0:degree
        basis(a+1) = nchoosek( degree, a ) * ( variate ^ a ) * ( ( 1 - variate ) ^ ( degree - a ) );
    end
end
```

```{=latex}
\begin{align*}
    \begin{array}{ll}
        \Matrix{B}^0(x)
        =
        \begin{bmatrix}
            x^0
        \end{bmatrix}
        %%%%%%%%%%%%%%%%
        &
        %%%%%%%%%%%%%%%%
        \Matrix{B}^1(x)
        =
        \begin{bmatrix}
            x^0-x^1 \\
            x^1
        \end{bmatrix}
        %%%%%%%%%%%%%%%%
        \\
        %%%%%%%%%%%%%%%%
        \Matrix{B}^2(x)
        =
        \begin{bmatrix}
            x^0 - 2x^1 + x^2 \\
            2x^1 - 2x^2 \\
            x^2
        \end{bmatrix}
        %%%%%%%%%%%%%%%%
        &
        %%%%%%%%%%%%%%%%
        \Matrix{B}^3(x)
        =
        \begin{bmatrix}
            x^0 - 3x^1 + 3x^2 - x^3 \\
            3x^0 - 6x^2 + 3x^3 \\
            3x^2 - 3x^3 \\
            x^3
        \end{bmatrix}
    \end{array}
\end{align*}
```

```{matlab}
%| echo: false
x = sym( "x", "real" );
domain = sym( [0, 1] );

figure
for degree = 0 : 3;
    subplot( 2, 2, degree + 1 )
    hold on
    bernstein_basis = BernsteinBasis( degree, x, domain );
    % latex( expand( bernstein_basis ) )
    for ii = 1 : length( bernstein_basis )
        fplot( bernstein_basis(ii), double( domain ), LineWidth=2, DisplayName="$B_" + num2str(ii) + "$" )
    end
    ax = gca;
    ax.YLim = [0, 1];
    legend( Location="northoutside", Orientation="horizontal" )
end
```

## The Legendre basis

The Legendre basis is the first of the orthogonal basis, so-called each basis polynomial is orthogonal in the $L^2$-norm to every other polynomial in the basis --- we'll define what this means later.
For now, it's enough to know that this orthogonality property provides a number of desirable numerical properties, even at high polynomial degree (especially in contrast to the Lagrange basis), and will prove especially useful when we later develop numerical quadrature schemes.

```{matlab}
%| output: false
function basis = LegendreBasis( degree, variate, domain )\
    param_domain = GetPolynomialParametricDomain( "Legendre" )
    variate = ChangeOfVariable( variate, domain, param_domain );
    basis = sym( zeros( degree + 1, 1 ) );
    for ii = 0 : degree
        if ii == 0
            basis(ii+1) = variate ^ 0 ;
        elseif ii == 1
            basis(ii+1) = variate ^ 1;
        else
            n = ii - 1;
            term1 = ( 2 * n + 1 ) * variate * basis(n+1);
            term2 = n * basis(n);
            basis(ii+1) = simplify ( ( term1 - term2 ) / ( n + 1 ) );
        end
    end
end
```

```{=latex}
\begin{align*}
    \begin{array}{ll}
        \Matrix{P}^0(x)
        =
        \begin{bmatrix}
            x^0
        \end{bmatrix}
        %%%%%%%%%%%%%%%%
        &
        %%%%%%%%%%%%%%%%
        \Matrix{P}^1(x)
        =
        \begin{bmatrix}
            x^0 \\
            x^1
        \end{bmatrix}
        %%%%%%%%%%%%%%%%
        \\
        %%%%%%%%%%%%%%%%
        \Matrix{P}^2(x)
        =
        \begin{bmatrix}
            x^0 \\
            x^1 \\
            -\frac{x^0}{2} + \frac{3x^2}{2}
        \end{bmatrix}
        %%%%%%%%%%%%%%%%
        &
        %%%%%%%%%%%%%%%%
        \Matrix{P}^3(x)
        =
        \begin{bmatrix}
            x^0 \\
            x^1 \\
            -\frac{x^0}{2} + \frac{3x^2}{2} \\
            -\frac{3x^1}{2} + \frac{5x^3}{2}
        \end{bmatrix}
    \end{array}
\end{align*}
```

```{matlab}
%| echo: false
x = sym( "x", "real" );
domain = sym( [-1, 1] );

figure
for degree = 0 : 3;
    subplot( 2, 2, degree + 1 )
    hold on
    legendre_basis = LegendreBasis( degree, x, domain );
    % latex( expand( legendre_basis ) )
    for ii = 1 : length( legendre_basis )
        fplot( legendre_basis(ii), double( domain ), LineWidth=2, DisplayName="$P_" + num2str(ii) + "$" )
    end
    ax = gca;
    ax.YLim = [-1, 1];
    legend( Location="northoutside", Orientation="horizontal" )
end
```

## The Chebyshev basis

The Chebyshev basis is another orthogonal basis, however its orthogonality is defined slighlty differently than the Legendre basis.
We will discuss this nuance later, but it is sufficient to say that it too has many beneficial numerical properties stemming from its orthogonality and is incredibly important in modern approximation theory.
Due to various transliterations of its namesake, [Pafnuty Chebyshev](https://en.wikipedia.org/wiki/Pafnuty_Chebyshev), it is sometimes written as *Tchebycheff*, *Tchebyshev* (French), or *Tschebyschow* (German).

```{matlab}
%| output: false
function basis = ChebyshevBasis( degree, variate, domain )
    param_domain = GetPolynomialParametricDomain( "Chebyshev" )
    variate = ChangeOfVariable( variate, domain, param_domain );
    basis = sym( zeros( degree + 1, 1 ) );
    for ii = 0 : degree
        if ii == 0
            basis(ii+1) = variate ^ 0;
        elseif ii == 1
            basis(ii+1) = variate ^ 1;
        else
            basis(ii+1) = ( 2 * variate * basis(ii) ) - basis(ii-1);
        end
    end
end
```

```{=latex}
\begin{align*}
    \begin{array}{ll}
        \Matrix{T}^0(x)
        =
        \begin{bmatrix}
            x^0
        \end{bmatrix}
        %%%%%%%%%%%%%%%%
        &
        %%%%%%%%%%%%%%%%
        \Matrix{T}^1(x)
        =
        \begin{bmatrix}
            x^0 \\
            x^1
        \end{bmatrix}
        %%%%%%%%%%%%%%%%
        \\
        %%%%%%%%%%%%%%%%
        \Matrix{T}^2(x)
        =
        \begin{bmatrix}
            x^0 \\
            x^1 \\
            -x^0 + x^2
        \end{bmatrix}
        %%%%%%%%%%%%%%%%
        &
        %%%%%%%%%%%%%%%%
        \Matrix{T}^3(x)
        =
        \begin{bmatrix}
            x^0 \\
            x^1 \\
            -x^0 + x^2 \\
            -3x^1 + 4x^3
        \end{bmatrix}
    \end{array}
\end{align*}
```

```{matlab}
%| echo: false
x = sym( "x", "real" );
domain = sym( [-1, 1] );

figure
for degree = 0 : 3;
    subplot( 2, 2, degree + 1 )
    hold on
    chebyshev_basis = ChebyshevBasis( degree, x, domain );
    % latex( expand( chebyshev_basis ) )
    for ii = 1 : length( chebyshev_basis )
        fplot( chebyshev_basis(ii), double( domain ), LineWidth=2, DisplayName="$T_" + num2str(ii) + "$" )
    end
    ax = gca;
    ax.YLim = [-1, 1];
    legend( Location="northoutside", Orientation="horizontal" )
end
```

## The Lagrange-Legendre Basis
```{matlab}
%| output: false
function basis = LagrangeLegendreBasis( degree, variate, domain )
    if degree > 0
        P = LegendreBasis( degree + 1, variate, domain );
        C = CompanionMatrix( P(end) );
        P_roots = eig( C );
        [~, sidx] = sort( real( vpa( P_roots ) ) );
        P_roots = real( vpa( P_roots(sidx) ) );
        node = P_roots;
        %node = ChangeOfVariable( P_roots, [P_roots(1), P_roots(end)], domain );
    else
        node = domain(1);
    end
    basis = sym( zeros( degree + 1, 1 ) );
    for ii = 1 : degree + 1
        basis(ii) = variate ^ 0;
        for jj = 1 : degree + 1
            if ii ~= jj
                basis(ii) = basis(ii) * ( ( variate - node(jj) ) / ( node(ii) - node(jj) ) );
            end
        end
    end
end
```

```{matlab}
%| echo: false
x = sym( "x", "real" );
domain = sym( [-1, 1] );

figure
for degree = 0 : 8;
    subplot( 3, 3, degree + 1 )
    hold on
    lagrange_legendre_basis = LagrangeLegendreBasis( degree, x, domain );
    % latex( expand( lagrange_legendre_basis ) )
    for ii = 1 : length( lagrange_legendre_basis )
        fplot( lagrange_legendre_basis(ii), double( domain ), LineWidth=2, MeshDensity=(degree + 1)*20, DisplayName="$L_" + num2str(ii) + "$" )
    end
    ax = gca;
    ax.YLim = [-0.5, 1.5];
    legend( Location="northoutside", Orientation="horizontal" )
end
```

## Other Basis Polynomials

There are a multitude of other basis polynomials which we will not show here.
Several of these basis that are commonly used are variations of the Lagrange basis, where the roots of the Legendre and Chebyshev basis are used as the nodes (roots) of the Lagrange basis.
The resulting basis, while perhaps not as commonly used as the aforementioned basis, inherit some of the beneficial numerical properties of their orthogonal progenitors.[^1]
Also included are various other orthogonal polynomials such as the Leguerre, Lobatto, Hermite, and Jacobi polynomials, to name a few.

[^1]: Such as minimizing the deleterious Runge phenomenon observed with high-order polynomial interpolants.

## A Polynomial Basis Interface

To simplify accessing the various basis polynomials later in this text, let's define an interface method:

```{matlab}
%| output: false
function basis = PolynomialBasisFunction( basis_name, degree, variate, domain )
        if basis_name == "Bernstein"
            basis = BernsteinBasis( degree, variate, domain );
        elseif basis_name == "Chebyshev"
            basis = ChebyshevBasis( degree, variate, domain );
        elseif basis_name == "Lagrange"
            basis = LagrangeBasis( degree, variate, domain );
        elseif basis_name == "Legendre"
            basis = LegendreBasis( degree, variate, domain );
        elseif basis_name == "Lagrange-Legendre"
            basis = LagrangeLegendreBasis( degree, variate, domain );
        elseif basis_name == "Monomial"
            basis = MonomialBasis( degree, variate, domain );
        end
    end
```