name: Run Default Tasks in Build File
on: [push]
jobs:
  my-job:
    name: Run MATLAB Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        id: setup-matlab
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
          release: R2024b
          products: >
            Symbolic_Math_Toolbox

      - name: Set MATLAB_ROOT
        run: |
          echo "MATLAB_ROOT=${{ steps.setup-matlab.outputs.matlabroot }}" >> $GITHUB_ENV
          export MATLAB_ROOT="${{ steps.setup-matlab.outputs.matlabroot }}"
          echo ${{ steps.setup-matlab.outputs.matlabroot }}
          echo $MATLAB_ROOT

      - name: Use MATLAB_ROOT in another step
        run: |
          echo "MATLAB_ROOT from env: ${{ env.MATLAB_ROOT }}"
          echo "MATLAB_ROOT from shell: $MATLAB_ROOT"

      - name: Run build
        uses: matlab-actions/run-build@v2