name: Run Default Tasks in Build File
on: [push]
jobs:
  my-job:
    name: Run MATLAB Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: >
            true
          release: >
            R2024b
          products: >
            Symbolic_Math_Toolbox
      - name: Print MATLAB root folder directly
        run: echo ${{ steps.setup-matlab.outputs.matlabroot }}

      - name: Print MATLAB root folder from env var
        env:
          MATLAB_ROOT: ${{ steps.setup-matlab.outputs.matlabroot }}
        run: echo $MATLAB_ROOT
        
      - name: Run build
        uses: matlab-actions/run-build@v2