name: Run Default Tasks in Build File
on: [push]
jobs:
  my-job:
    name: Run MATLAB Build
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: >
            true
          release: >
            R2024b
          products: >
            Symbolic_Math_Toolbox
      - name: Run build
        uses: matlab-actions/run-build@v2