on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: >
            true
          release: >
            R2024b
          products: >
            Symbolic_Math_Toolbox

      - name: Build Matlab
        uses: matlab-actions/run-build@v2

      - name: Set MATLAB_ROOT
        run: echo "MATLAB_ROOT=${{ env.MATLAB_ROOT }}" >> $GITHUB_ENV
        env:
          MATLAB_ROOT: ${{ steps.setup-matlab.outputs.matlab-root }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install pip requirements
        run: |
          set MATLABROOT=${MATLAB_ROOT}
          pip install -r mkernel_python_requirements.txt

      - name: Manually build and install matlabengine
        run: |
          cd %MATLAB_ROOT%\extern\engines\python
          python setup.py install
        env:
          MATLAB_ROOT: ${{ env.MATLAB_ROOT }}
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}